# Introduction to Numpy

-   **N-dimensional array** is an object, capable of holding data elements of same type and of a fixed size in multiple dimensions.

In [1]:
import numpy as np

### 1-D array creation.

In [2]:
one_D_lst = [5, 6, 10, 12, 43, 65]
x = np.array(one_D_lst)
x

array([ 5,  6, 10, 12, 43, 65])

### 2-D array creation

In [3]:
two_D_lst = [[3, 5, 65, -2], [9, 78, -98, 64]]
y = np.array(two_D_lst)
y

array([[  3,   5,  65,  -2],
       [  9,  78, -98,  64]])

### Array Attributes:

-   **ndim** : Returns number of dimensions.

-   **shape** : Returns Shape in tuple.

-   **size** : Total number of elements.

-   **dtype** : Type of each element.

-   **itemsize** : Size of each element in Bytes.

-   **nbytes** : Total bytes consumed by all elements.

-   **flags** : Information about the memory layout of the array.

In [4]:
print(f'Array Type: {type(x)}\nDimention: {x.ndim}\nShape: {x.shape}')
print(f'Size: {x.size}\nElement Type: {x.dtype}\nSize of Each Element(Bytes): {x.itemsize}')
print(f'Total bytes of all elements: {x.nbytes}\nMemory Info:\n{x.flags}')

Array Type: <class 'numpy.ndarray'>
Dimention: 1
Shape: (6,)
Size: 6
Element Type: int64
Size of Each Element(Bytes): 8
Total bytes of all elements: 48
Memory Info:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [5]:
print(f'Array Type: {type(y)}\nDimention: {y.ndim}\nShape: {y.shape}')
print(f'Size: {y.size}\nElement Type: {y.dtype}\nSize of Each Element(Bytes): {y.itemsize}')
print(f'Total bytes of all elements: {y.nbytes}\nMemory Info:\n{y.flags}')

Array Type: <class 'numpy.ndarray'>
Dimention: 2
Shape: (2, 4)
Size: 8
Element Type: int64
Size of Each Element(Bytes): 8
Total bytes of all elements: 64
Memory Info:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### Changing Datatype of Elements.

In [6]:
y = np.array([[6, 9, 5],
              [10, 82, 34]],
             dtype=np.float64)
print(y)
print(y.dtype)

[[ 6.  9.  5.]
 [10. 82. 34.]]
float64


# Creating ndarrays

-   From Python built-in datatypes : **lists or tuples**.

-   Using Numpy array creation methods like **ones, ones_like, zeros, zeros_like**.

-   Using Numpy numeric sequence generators.

-   Using Numpy **random** module.

-   By reading data from a file.


### ndarrays from Lists

In [7]:
a = [[[4.1, 2.5], [1.1, 2.3], [9.1, 2.5]],
     [[8.6, 9.9],[3.6, 4.3], [6.6, 0.3]]]

x = np.array(a, dtype='float64')

print(type(x), x.ndim, x.shape)

<class 'numpy.ndarray'> 3 (2, 3, 2)


### Array Creation Methods

In [8]:
# Using zeros method.
x = np.zeros(shape=(2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# Using full method.
x = np.full(shape=(2, 4), fill_value=9.8)
x

array([[9.8, 9.8, 9.8, 9.8],
       [9.8, 9.8, 9.8, 9.8]])

In [10]:
# Unsing zeros_like method.
arr = [[[2.3, 9.6], [23.6, 98.5], [3.4, 4.5]],
     [[3.14, 87.5], [7.4, 22.7], [8.6, 75.4]]]
print(arr)

x = np.zeros_like(a=arr)
print(x)
print(type(x), x.ndim, x.shape)

[[[2.3, 9.6], [23.6, 98.5], [3.4, 4.5]], [[3.14, 87.5], [7.4, 22.7], [8.6, 75.4]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
<class 'numpy.ndarray'> 3 (2, 3, 2)


In [11]:
# Using full_like method.
arr = [[3.42, 3.67], [9.87, 20.3]]
print(arr)

x = np.full_like(a=arr, fill_value=10.34)
print(x)
print(type(x), x.ndim, x.shape)

[[3.42, 3.67], [9.87, 20.3]]
[[10.34 10.34]
 [10.34 10.34]]
<class 'numpy.ndarray'> 2 (2, 2)


In [12]:
# Using ones method.
x = np.ones(shape=(3,2))
print(x)
print(type(x), x.ndim, x.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'> 2 (3, 2)


In [13]:
# Using empty method.
x = np.empty(shape=(2,1))
x

array([[0.],
       [0.]])

In [14]:
# np.eye(n, m) defines a 2D identity matrix. 
# The elements where i=j (row index and column index are equal) are 1 and the rest are 0.
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Numeric Sequence Generators

- arrange: `numpy.arange([start, ]stop, [step, ]dtype=None)`
- linespace `numpy.linspace(start, stop, #num of elements, endpoint=True, retstep=False, dtype=None)`

In [15]:
# Using arrage method.
x = np.arange(3, 15, 2.5)
x

array([ 3. ,  5.5,  8. , 10.5, 13. ])

In [16]:
# Using linespace method.
x = np.linspace(10, 20, 5)
x

array([10. , 12.5, 15. , 17.5, 20. ])

### Random Numbers Generator

The method **default_rng()** is used to create a random number generator that is used to obtain samples from different distributions.

In [17]:
# Generate one random float uniformly distributed over the range [0, 1).
rng = np.random.default_rng()
rng.random()

0.6454541239177911

In [18]:
# Generate random 1-D array where each element is in range [0, 1).
rng.random(size=5)

array([0.2414636 , 0.54944156, 0.15496556, 0.74113108, 0.82962548])

In [19]:
# Generate random 2-D array where each element is in range [0, 1).
rand_arr1 = rng.random(size=(3, 4))
rand_arr1

array([[0.28093632, 0.21349741, 0.5362496 , 0.86799662],
       [0.22103439, 0.80326844, 0.15473018, 0.25966017],
       [0.6508982 , 0.65987907, 0.63900787, 0.75652635]])

In [20]:
# Generate random 2-D array where each element is integer and in range 5-60.
rand_arr2 = rng.integers(5, 60, size=(4, 5))
rand_arr2

array([[59, 49, 42, 41,  8],
       [54,  5, 44, 29, 49],
       [39, 11, 56, 37, 40],
       [11, 43, 27,  5, 11]])

In [21]:
# Generate an array of 10 numbers according to a unit Gaussian distribution.
rand_arr3 = rng.standard_normal(10)
rand_arr3

array([ 0.26429455, -0.38378386,  1.08009275, -1.07881101,  0.47229674,
        1.69313136,  1.10898784, -0.94191763, -0.66333087, -0.20983216])

In [34]:
# Generate an array of 10 numbers in normal distribution with mean 10 and standard deviation 2.
rand_arr4 = 10 + 2 * rng.standard_normal(10)
print(rand_arr4)
# Calculate Mean and Standard Deviation.
print(f'Mean: {rand_arr4.mean()}\nSTD: {rand_arr4.std()}')

[10.04838881  8.75430363 10.29402119 13.93189795  9.89016015 12.38768006
 13.51551117 11.88511442 11.07772433  8.06116479]
Mean: 10.984596649256368
STD: 1.8426120868182372


In [24]:
# Generate a binomial distribution of flipping a coin 100 times.
outcome = 1
probability = 0.5
total_trials = 100

samples = rng.binomial(n=outcome, p=probability, size=total_trials)
print(samples)

total_probability = sum(samples)/total_trials
print(total_probability)

[0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 1 0 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 0 1 1 0
 1 1 1 1 0 1 0 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0 1 1
 1 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 0 1 1 1 0 0 0 0]
0.52


##### Excercise 1

Write a function **arr** which can accept four parameters **a, x, y and z**, then perform the following operations:

- Define a ndarray **x1**, having first **a** even numbers ( Zero not included).
- Define a ndarray **x2**, having equally spaced **z** numbers between **x** and **y**.
- Print **x1** and **x2**.

In [25]:
a, x, y, z = 41, 0, 30, 15

def arr(a, x, y, z):
    # Creating x1
    x1 = np.arange(2, a, 2)

    # Creating x2
    x2 = np.linspace(x, y, z)

    print(x1)
    print(x2)

arr(a, x, y, z)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[ 0.          2.14285714  4.28571429  6.42857143  8.57142857 10.71428571
 12.85714286 15.         17.14285714 19.28571429 21.42857143 23.57142857
 25.71428571 27.85714286 30.        ]


##### Excercise 2

Write a function **array_3d** which can accept four parameters **n, x, y, z**, then perform the following:

- Simulate a random normal distribution for **n**, whose mean is **5** and standard deviation **2.5**. Capture the result in **x1**.
    - Find the product of the number of element in the array and the size of one array element in byte. Then store it in the variable **A**.
    **Note:** Set numpy seed value 100.

- Define a random 3-D array **x2** of shape **(x, y, z)** and of numbers **between 0 and 1**.

- Print the value of A and x2.

In [26]:
n, x, y, z = 20, 3, 4, 2

def array_3d(n, x, y, z):
    mean, stddev = 5, 2.5

    # Random Generator.
    rng = np.random.default_rng(seed=100)

    # Normal Distribution.
    x1 = mean + stddev * rng.standard_normal(size=n)

    # Calculate total size.
    A = x1.size * x1.itemsize

    # Creating 3-D array.
    x2 = rng.random(size=(x, y, z))

    print(A)
    print(x2)

array_3d(n, x, y, z)

160
[[[0.99767449 0.97862192]
  [0.39356804 0.32192526]
  [0.86218065 0.7993249 ]
  [0.69143063 0.40851785]]

 [[0.38976513 0.1316484 ]
  [0.62549749 0.08240137]
  [0.27457299 0.65611703]
  [0.01467603 0.83453217]]

 [[0.07239908 0.52412082]
  [0.54655052 0.22724696]
  [0.95597822 0.34096385]
  [0.50470744 0.86738361]]]


In [27]:
n, x, y, z = 20, 3, 4, 2

def array_3d(n, x, y, z):    
    mean, stddev = 5, 2.5

    # Setting Seed to 100.
    np.random.seed(100)

    # Normal Distribution.
    x1 = mean + stddev * np.random.randn(n)

    # Calculate total size.
    A = x1.size * x1.itemsize

    # Creating 3-D array.
    x2 = np.random.random(size=(x, y, z))

    print(A)
    print(x2)

array_3d(n, x, y, z)

160
[[[0.00568851 0.25242635]
  [0.79566251 0.01525497]
  [0.59884338 0.60380454]
  [0.10514769 0.38194344]]

 [[0.03647606 0.89041156]
  [0.98092086 0.05994199]
  [0.89054594 0.5769015 ]
  [0.74247969 0.63018394]]

 [[0.58184219 0.02043913]
  [0.21002658 0.54468488]
  [0.76911517 0.25069523]
  [0.28589569 0.85239509]]]
