# NumPy Array Shape Manipulation

- reshape
- vstack
- hstack
- vsplit
- hsplit

In [46]:
import numpy as np

# Random generator.
rng = np.random.default_rng(seed=100)

#### reshape
Shape of an array can be changed using reshape.

In [47]:
arr1 = rng.integers(10, 100, 8)
print(arr1)
arr2 = arr1.reshape(2, 4)
print(arr2)
arr3 = arr1.reshape(2, 2, 2)
print(arr3)

[79 85 21 63 17 35 49 13]
[[79 85 21 63]
 [17 35 49 13]]
[[[79 85]
  [21 63]]

 [[17 35]
  [49 13]]]


#### vstack

Stacking arrays vertically.

In [48]:
x = np.array([(1, 3), (5, 4)])
y = np.array([(12, 43), (55, 74)])
z = np.vstack((y, x))

print(f'x:\n {x}\n\ny:\n {y}\n\nz:\n {z}')

x:
 [[1 3]
 [5 4]]

y:
 [[12 43]
 [55 74]]

z:
 [[12 43]
 [55 74]
 [ 1  3]
 [ 5  4]]


#### hstack

Stacking arrays horizontally.

In [49]:
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
z = np.array([[-5, 5], [-6, 6]])
k = np.hstack((x,y,z))

print(f'x:\n {x}\n\ny:\n {y}\n\nz:\n {z}\n\nk:\n {k}')

x:
 [[-1  1]
 [-3  3]]

y:
 [[-2  2]
 [-4  4]]

z:
 [[-5  5]
 [-6  6]]

k:
 [[-1  1 -2  2 -5  5]
 [-3  3 -4  4 -6  6]]


#### vsplit

- Arrays can be split vertically **(axis = 0)** using the generic vsplit method.

- It is also possible to split at specific row numbers using vsplit.

In [50]:
x = np.arange(30).reshape(6, 5)
print(f'x:\n {x}')

# Splits array in 2 parts row-wise.
splits = np.vsplit(x, 2)

idx = 0
for arr in splits:
    print(f'\n\nsplits[{idx}]:\n {arr}')
    idx += 1


x:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


splits[0]:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


splits[1]:
 [[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [51]:
# Spliting Vertically into three arrays
splits = np.vsplit(x, (2, 5))
idx = 0
for arr in splits:
    print(f'\n\nsplits[{idx}]:\n {arr}')
    idx += 1



splits[0]:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


splits[1]:
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


splits[2]:
 [[25 26 27 28 29]]


#### hsplit

Splitting arrays Horizontally. **(axis = 1)**

In [52]:
x = np.arange(10).reshape(2, 5)
print(f'x:\n {x}')

splits = np.hsplit(x, (2, 4))

idx = 0
for arr in splits:
    print(f'\n\nsplits[{idx}]:\n {arr}')
    idx += 1


x:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


splits[0]:
 [[0 1]
 [5 6]]


splits[1]:
 [[2 3]
 [7 8]]


splits[2]:
 [[4]
 [9]]


### Flatrening of Numpy Array

In [53]:
x = np.arange(12).reshape(3, 4)
print(x)

# to list.
print('\nTo List:')
print(x.tolist())

# flatten
print('\nFlatten:')
for num in x.flat:
    print(num, end=' ')

# ravel 
print('\n\nravel:')
print(x.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

To List:
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

Flatten:
0 1 2 3 4 5 6 7 8 9 10 11 

ravel:
[ 0  1  2  3  4  5  6  7  8  9 10 11]


# Basic Operations on NumPy Arrays

- Operations on NumPy arrays (ndarray) are carried out element level.

In [54]:
x = np.arange(4).reshape(2,2)
print(x.tolist())
print(x.ravel())
for elem in x.flat:
    print(elem)

[[0, 1], [2, 3]]
[0 1 2 3]
0
1
2
3


In [55]:
x = np.arange(6).reshape(2, 3)
print(f'x:\n {x}')

# Scalar operations.
print(f'\nx + 10:\n {x + 10}')
print(f'\nx * 3:\n {x * 3}')
print(f'\nx % 2:\n {x % 2}')

x:
 [[0 1 2]
 [3 4 5]]

x + 10:
 [[10 11 12]
 [13 14 15]]

x * 3:
 [[ 0  3  6]
 [ 9 12 15]]

x % 2:
 [[0 1 0]
 [1 0 1]]


In [56]:
x = np.array([[-1, 1], [-2, 2]])
y = np.array([[4, -4], [5, -5]])

print(f'x:\n {x}\ny:\n {y}')

# Element wise array operations.
print(f'\nx + y:\n {x + y}')
print(f'\nx * y:\n {x * y}')

x:
 [[-1  1]
 [-2  2]]
y:
 [[ 4 -4]
 [ 5 -5]]

x + y:
 [[ 3 -3]
 [ 3 -3]]

x * y:
 [[ -4  -4]
 [-10 -10]]


In [57]:
# Matrix Multiplication.
A = rng.integers(5, 20, 6).reshape(2, 3)
B = rng.integers(5, 15, 6).reshape(3, 2)

print(f'A:\n {A}\nB:\n {B}')

C = A @ B

print(f'\nC = A x B:\n {C}')

A:
 [[13 19 19]
 [13 11 16]]
B:
 [[14 14]
 [ 5 11]
 [12  6]]

C = A x B:
 [[505 505]
 [429 399]]


## Broadcasting

- The **Broadcasting** feature of the numpy arrays enables to perform operations on arrays with varying size and shape.

### General broadcasting rules

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

1. they are equal, or

2. one of them is 1.

If these conditions are not met, a `ValueError: operands could not be broadcast together` exception is thrown, indicating that the arrays have incompatible shapes.

Input arrays do not need to have the same number of dimensions. The resulting array will have the same number of dimensions as the input array with the greatest number of dimensions, where the size of each dimension is the largest size of the corresponding dimension among the input arrays. Note that missing dimensions are assumed to have size one.

```
Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3
```

````
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5
````

In [58]:
x = np.array([[-1, 1], [-2, 2]])
y = np.array([-10, 10])

print(f'x:\n {x}\ny:\n {y}')
print(f'\nx * y:\n {x * y}')

x:
 [[-1  1]
 [-2  2]]
y:
 [-10  10]

x * y:
 [[10 10]
 [20 20]]


In [59]:
def show_array(x):
    print(f'\n{x}\nShape - {x.shape}')

a = np.arange(10, 130, 10).reshape(4, 3)
b = np.arange(1, 4)

show_array(a)
show_array(b)

# Feasible for Broadcast.
show_array(a + b)

c = rng.integers(1, 10, 4)
show_array(c)

# Not Feasible for Broadcast. Throws Exception.
d = a - c


[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Shape - (4, 3)

[1 2 3]
Shape - (3,)

[[ 11  22  33]
 [ 41  52  63]
 [ 71  82  93]
 [101 112 123]]
Shape - (4, 3)

[5 9 7 3]
Shape - (4,)


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

## NumPy Universal Functions

Numpy provides a lot of mathematical functions, in the form of Universal functions.

- square
- sin, cos


In [ ]:
x = np.array([[0,1], [2,3]])
print(x)
print(np.square(x), end='\n\n')
print(np.sin(x))
print(x.sum(), end='\n\n')
print(x.sum(axis=0), end='\n\n')
print(x.sum(axis=1))

[[0 1]
 [2 3]]
[[0 1]
 [4 9]]

[[0.         0.84147098]
 [0.90929743 0.14112001]]
6

[2 4]

[1 5]


###### Example: Statistics Functions

Write a function **array_stat** which accepts three parameters **n, m and sd** and perform following operations:

- Create and array **x** of shape **(n,)**, having **n** random numbers from a normal distribution of mean **m** and standard deviation **sd**.

- Print the *Mean, Standard Deviation and Variance* of **x**.

**Note**: Set random seed to 100.

*Here, we are comparing results by creating random normal distributions using two different methods.*

In [60]:
import numpy as np 

# Function: array_stat1
def array_stat1(n, m, sd):
    # Set the random seed to 100.
    np.random.seed(100)

    # Create the array x with normal distribution of mean m and standard deviation sd.
    x = m + sd * np.random.randn(n)

    print('\narray_stat1:\n')
    print(f'Mean - {x.mean()}')
    print(f'Standard Deviation - {x.std()}')
    print(f'Variance - {x.var()}')

# Function: array_stat2
def array_stat2(n, m, sd):
    # Set the random seed to 100.
    rng = np.random.default_rng(seed=100)

    # Create the array x with normal distribution of mean m and standard deviation sd.
    x = m + sd * rng.standard_normal(size=n)

    print('\narray_stat2:\n')
    print(f'Mean - {x.mean()}')
    print(f'Standard Deviation - {x.std()}')
    print(f'Variance - {x.var()}')

# Call the functions.
n , m, sd = 60, 12, 4
array_stat1(n , m, sd)
array_stat2(n , m, sd)


array_stat1:

Mean - 11.632586334459914
Standard Deviation - 3.6706703818132898
Variance - 13.473821051921323

array_stat2:

Mean - 12.426310795467234
Standard Deviation - 3.9976369504572498
Variance - 15.98110118766114
