# Indexing, Slicing of NumPy Array

- **Indexing**: Indexing refers to accessing elements of the array. Index starts from 0.

- **Slicing**: Slicing refers to extracting a portion of existing array. A slice object is of the form **start:end:step**. The **end** element are not included in result of slicing.

In [1]:
import numpy as np

### 1-D Array

In [10]:
x = np.arange(10, 50, 3)
print(x)

# Indexing
print(x[0])
print(x[3])
print(x[-1])
print(x[-4])

# Slicing.
print(x[1:6])
print(x[1:6:2])
print(x[::-1]) # Reverse of array.
print(x[3:])

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]
10
19
49
40
[13 16 19 22 25]
[13 19 25]
[49 46 43 40 37 34 31 28 25 22 19 16 13 10]
[19 22 25 28 31 34 37 40 43 46 49]


#### Slicing Object.

In [43]:
x = np.arange(10, 50, 3)
slice_obj = slice(3, 8)

x_slice = x[slice_obj]
x_slice_cp = x[slice_obj].copy()

print('Original:\n', x, '\nSlice:\n', x_slice, '\nCopy of Slice:\n', x_slice_cp)

print('\nAfter Manipilation...\n')
x[slice_obj] = 0

print('Original:\n', x, '\nSlice:\n', x_slice, '\nCopy of Slice:\n', x_slice_cp)

Original:
 [10 13 16 19 22 25 28 31 34 37 40 43 46 49] 
Slice:
 [19 22 25 28 31] 
Copy of Slice:
 [19 22 25 28 31]

After Manipilation...

Original:
 [10 13 16  0  0  0  0  0 34 37 40 43 46 49] 
Slice:
 [0 0 0 0 0] 
Copy of Slice:
 [19 22 25 28 31]


### 2-D Array

In [14]:
data = np.arange(10, 45, 3).reshape(3, 4)
data

array([[10, 13, 16, 19],
       [22, 25, 28, 31],
       [34, 37, 40, 43]])

In [28]:
# Indexing.
print(data[1])
print(data[1, 2])
print(data[-2, -1])

# Slicing.
print(data[1:2, 1:3])
print(data[1:, 1:3])
print(data[1::-1, 1:3])
print(data[:, 2:3])

[22 25 28 31]
28
31
[[25 28]]
[[25 28]
 [37 40]]
[[25 28]
 [13 16]]
[[16]
 [28]
 [40]]


In [44]:
# Slice array manipilation.
data = np.arange(10, 45, 3).reshape(3, 4)
data_slice = data[1:, 2:]
data_slice_cp = data[1:, 2:].copy()
print('Original:\n', data, '\nSlice:\n', data_slice, '\nCopy of Slice:\n', data_slice_cp)

print('\nAfter Slice Manipulation...\n')
# Manipulation of data slice.
data[1:, 2:] = 1
print('Original:\n', data, '\nSlice:\n', data_slice, '\nCopy of Slice:\n', data_slice_cp)

Original:
 [[10 13 16 19]
 [22 25 28 31]
 [34 37 40 43]] 
Slice:
 [[28 31]
 [40 43]] 
Copy of Slice:
 [[28 31]
 [40 43]]

After Slice Manipulation...

Original:
 [[10 13 16 19]
 [22 25  1  1]
 [34 37  1  1]] 
Slice:
 [[1 1]
 [1 1]] 
Copy of Slice:
 [[28 31]
 [40 43]]


### Higher Dimentional Array

In [61]:
info = np.arange(1, 53, 3).reshape(3, 2, 3)
info

array([[[ 1,  4,  7],
        [10, 13, 16]],

       [[19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52]]])

In [65]:
print(info[1])
print(info[1, :, 1])
print(info[1:, 1, :])

[[19 22 25]
 [28 31 34]]
[22 31]
[[28 31 34]
 [46 49 52]]


#### Iterating using 'nditer'

- **nditer** method of numpy creates an iterator, which enable accessing each element one after the other.

In [66]:
x = np.array([[0,1], [2, 3]])
for a in np.nditer(x):
    print(a)

0
1
2
3


#### Boolean Indexing

- Checking if every element of an array satisfies a condition, results in a Boolean array.

- This Boolean array can be used as index to filter elements that satisfy the condition.

In [69]:
x = np.arange(1,11).reshape(2,5)
print('Original:\n', x)
cond = x % 2 == 0
print('\nBoolean Result:\n', cond)
print('\nBoolean Indexed Array:\n', x[cond])

Original:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Boolean Result:
 [[False  True False  True False]
 [ True False  True False  True]]

Boolean Indexed Array:
 [ 2  4  6  8 10]


##### Excercise

Write a fuction **array_index** which accepts three numbers **n, n_row, n_col** and performs the array operations given below:

- Create a array **x** of shape **(n_row, n_col)** having first **n** natural numbers.

- Print elements of last row.

- Print elements of middle column.

- Print elements, overlapping first two rows and last three columns.

In [84]:
def array_index(n, n_row, n_col):
    x = np.arange(n).reshape(n_row, n_col)

    print('Array:\n', x)

    print('\nElements of the last row: ', x[-1])

    mid_col = n_col // 2

    print('\nElements of the middle column: ', x[:, mid_col])
    print('\nElements overlapping first two rows and last three columns:\n', x[:2, -3:])

n = 40
n_row = 4
n_col = 10

array_index(n, n_row, n_col)

Array:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]

Elements of the last row:  [30 31 32 33 34 35 36 37 38 39]

Elements of the middle column:  [ 5 15 25 35]

Elements overlapping first two rows and last three columns:
 [[ 7  8  9]
 [17 18 19]]
