# Hypothesis Testing

- **Hypothesis Testing** is used in *inferential statistics* where sample data is used to make inference or conclusion of the unknown parameters of population data.

- In a Hypothesis Testing, a **Null Hypothesis (Ho)** represents currently accepted the state of knowledge, and an **Alternative Hypothesis (Ha)** represents a new claim which challenges the currently accepted state of knowledge.

## Hypothesis Testing Mechanism

- Define the **Null Hypothesis (Ho)**: The baseline of assumption.
    
- Define the **Alternate Hypothesis (Ha)**: The new claim. 

- Perform the **Statistical Experiments**

    - Colleting sample.
    - Perform the Statistical Test/Analysis (Z-score, T-test, chi-square test etc.)

- Define the **decision bounary** using p-value.

- Accept or Reject the Null Hypothesis (Ho).



## p-Value

- The **p-value or probability value** is a number between **0 and 1**.

- It is the probability of obsuving your result/data if the Null Hypothesis (Ho) is true.

- A **low p-value** represents by random chance your sample data is **NOT** likely to occur if the Null Hypothesis is true. This provides **stiong evidence to reject the Null Hypothesis (Ho)**.

- A **high p-value** represents by random chance your sample data is likely to occur if the Null Hypothesis is true. This **does NOT** provide **enough evidence to reject the Null Hypothesis (Ho)**.

## Confidence Interval (CI) and Significance Level (alpha)

- **Confidence Interval (CI)** is the *pre-defined percentage of confidence* by which we can estabilish the conclusion of a Hypothesis Testing.

- We generally set **95%** confidence interval of any Hypothesis testing. This means, we can say with **95%** confidence, we can accept or reject the Null Hypothesis.

- We calculate **Significance Level (alpha)** by using following formula:

`alpha = 1 - CI`

- So, for if **CI = 95%**, 

`alpha = 1 - CI = 1 - 0.95 = 0.05`

### Comparision of p-value with Significance Level (alpha)

- if **p-value < alpha**: *Reject* the null hypothesis
- else if **p-value >= alpha**: We *failed to reject* the null hypothesis.

### Example of Hypothesis Testing

There is a new drug in the market that claims to reduce blood pressure. Please perform Hypothesis testing with **97%** confidence to collect samples and testing the results.

### Solution

- **Null Hypothesis (Ho)**: The new drug has no effect on blood pressure.

- **Alternate Hypothesis (Ha)**: The new drug reduces the blood pressure.

- Now, we collect sample patient data and calculated p-value as **0.0223**. So, there are **2.23%** chance in our sample data that Null Hypothesis is true.

- CI = 97% = 0.97, so alpha = 1 - 0.97 = 0.03.

- Now, **0.0223 < 0.03**, So we reject the Null Hypothesis (Ho).

> With the Hypothesis testing, we conclude, with 97% confidence, The new drug reduces the blood pressure.

## Choosing Test Statistics

The methods used for performing t-test are shown below.

- `stats.ttest_1samp(a, popmean, axis=0, nan_policy='propagate', alternative='two-sided')`: This is a test for the null hypothesis that the expected value (mean) of a sample of independent observations a is equal to the given population mean, popmean. Tests if the **population mean** is available.

    - **a**: Sample data
    - **popmean**: Population Mean
    - **alternative**: Alternative Hypothesis Type: ‘two-sided’, ‘less’, ‘greater’. This parameter is present in all the ttest functions.

- It returns follows:
    
    - The t-statistic.
    - The p-value associated with the given alternative.
    - The number of degrees of freedom used in calculation of the t-statistic; this is one less than the size of the sample.

    
- `stats.ttest_ind(a, b)`: Tests if the means of two independent samples are equal. This is a test for the null hypothesis that 2 independent samples have identical average (expected) values. This test assumes that the populations have identical variances by default.

    - **a, b** is the two independent samples.


- `stats.ttest_rel(a, b)`: Tests if the means of two paired samples are equal. This is a test for the null hypothesis that two related or repeated samples have identical average (expected) values.

    - **a, b** is the two paired samples.

In [1]:
import scipy.stats as stats
import numpy as np
rng = np.random.default_rng(seed=1000)

#### Example: One Sample test, both sided

- The average height of the residents of a city is **168cm**.

- A doctor collects a **36** sample data of residents heights as follows:

[168.25, 167.61, 176.05, 177.19, 170.11, 164.59, 170.28, 169.66, 166.08, 175.46, 173.38, 164.0, 172.95, 163.93, 167.81, 166.04, 166.6, 169.5, 167.65, 168.27, 174.62, 168.33, 171.15, 163.51, 170.25, 172.22, 169.98, 167.21, 173.6, 175.17, 170.09, 175.74, 174.64, 170.6, 170.86, 173.37]

- He believes the average height of the residents is **not 168cm**. 

- With **95%** confidence please check if doctors assumption is correct or not.


In [2]:
# Input data.
sample_data = [168.25, 167.61, 176.05, 177.19, 170.11, 164.59, 170.28, 169.66, 166.08, 175.46, 173.38, 164.0, 172.95, 163.93, 167.81, 166.04, 166.6, 169.5, 167.65, 168.27, 174.62, 168.33, 171.15, 163.51, 170.25, 172.22, 169.98, 167.21, 173.6, 175.17, 170.09, 175.74, 174.64, 170.6, 170.86, 173.37]
mean = 168
CI = 0.95
alpha = 1 - CI

# Null Hypothesis (Ho): mean = 168 cm.
# Alternative Hypothesis (Ha): mean <> 168 cm.

# Perform test
test = stats.ttest_1samp(sample_data, popmean=mean)
p_value = test.pvalue

print(f'p-value of the test: {p_value}')
print(f'Significance Level (alpha) of the test: {alpha}')

# Conclusion
if p_value < alpha:
    print('\nWe reject the null hypothesis.')
    print(f'So we conclude, with {CI * 100}% confidence, \nThe average height of the residents is not 168 cm.')
else:
    print('\nWe failed to reject the null hypothesis.')

p-value of the test: 0.0012765503149234966
Significance Level (alpha) of the test: 0.050000000000000044

We reject the null hypothesis.
So we conclude, with 95.0% confidence, 
The average height of the residents is not 168 cm.


#### Example: One Sample Test, one sided (less)

- A factory manufactures bulb with an average warranty of **5 years**.

- One quality controller doubted that the bulb will malfuction in **less than 5 years**.

- So he collected samples of bulb warranty data of **40** cases and found following data:

[4.54, 4.46, 5.54, 5.69, 4.78, 4.07, 4.8, 4.72, 4.26, 5.46, 5.2, 4.0, 5.14, 3.99, 4.48, 4.26, 4.33, 4.7, 4.46, 4.54, 5.36, 4.55, 4.91, 3.93, 4.8, 5.05, 4.76, 4.41, 5.23, 5.43, 4.78, 5.5, 5.36, 4.84, 4.87, 5.2, 5.01, 4.18, 4.61, 5.3]

- He found average warranty period in the sample data is **4.78 years**.

- With **98%** confidence, is there enough evidence to support the idea of warranty period should be revised?

In [3]:
# Input Values
sample_data = [4.54, 4.46, 5.54, 5.69, 4.78, 4.07, 4.8, 4.72, 4.26, 5.46, 5.2, 4.0, 5.14, 3.99, 4.48, 4.26, 4.33, 4.7, 4.46, 4.54, 5.36, 4.55, 4.91, 3.93, 4.8, 5.05, 4.76, 4.41, 5.23, 5.43, 4.78, 5.5, 5.36, 4.84, 4.87, 5.2, 5.01, 4.18, 4.61, 5.3]
pop_mean = 5
CI = 0.98
alpha = 1 - CI

# Null Hypothesis (Ho): Average Warranty of Bulbs = 5 Years.
# Alternative Hypothesis (Ha): Average Warranty of Bulbs < 5 Years.
# Perform Test.
test = stats.ttest_1samp(a=sample_data, popmean=pop_mean, alternative='less')
p_value = test.pvalue

print(f'p-value of the test: {p_value}')
print(f'Significance Level of the test: {alpha}')

# Conclusion.
if p_value < alpha:
    print(f'\nWe reject the null hypothesis. So we conclude, with {CI * 100}% confidence,\nAverage Warranty of Bulbs < 5 Years.')
else:
    print('\nWe failed to reject the null hypothesis.')

p-value of the test: 0.0036533276772702495
Significance Level of the test: 0.020000000000000018

We reject the null hypothesis. So we conclude, with 98.0% confidence,
Average Warranty of Bulbs < 5 Years.


#### Example: Two Sample test.

- We want to know whether or not the mean weight between two different species of turtles is equal with **95%** confidence.

- To test this, we collect a simple random sample of turtles from each species with the following weights:

**Sample 1**: 300, 315, 320, 311, 314, 309, 300, 308, 305, 303, 305, 301, 303

**Sample 2**: 335, 329, 322, 321, 324, 319, 304, 308, 305, 311, 307, 300, 305

In [4]:
# Input Data.
sample1 = [300, 315, 320, 311, 314, 309, 300, 308, 305, 303, 305, 301, 303]
sample2 = [335, 329, 322, 321, 324, 319, 304, 308, 305, 311, 307, 300, 305]
CI = 0.95
alpha = 1 - CI

# Null Hypothesis (Ho): Mean of Sample1 = Mean of Sample2
# Alternate Hypothesis (Ha): Mean of Sample1 <> Mean of Sample2
# Perform test.
test = stats.ttest_ind(a = sample1, b = sample2)
print('p-value of the test: ', test.pvalue)
print('alpha of the test: ', alpha)

# Conclusion.
if test.pvalue < alpha:
    print('\nWe reject Null Hypothesis.')
    print(f'Hence, we conclude with {CI * 100}% confidence,\nthe mean of weights of two turtle species are not same.')
else:
    print('We failed to reject the Null Hypothesis.')

p-value of the test:  0.04633501389516513
alpha of the test:  0.050000000000000044

We reject Null Hypothesis.
Hence, we conclude with 95.0% confidence,
the mean of weights of two turtle species are not same.


### Example: Paired Sample test

- Suppose we want to know whether or not a certain training program is able to increase the max vertical jump (in inches) of basketball players.

- We took 12 basketball players and collect the sample of max jump heights initially.

**Before:** 22, 24, 20, 19, 19, 20, 22, 25, 24, 23, 22, 21

- Then those 12 players undegoes into a training program for a month. After a month, we have taken the following sample of max jump heights:

**After**: 23, 25, 20, 24, 18, 22, 23, 28, 24, 25, 24, 20

- Now with **95%** confidence determine if the training program is able to increase the max vertical jump of basketball players. 

In [5]:
# Input values.
before_state = [22, 24, 20, 19, 19, 20, 22, 25, 24, 23, 22, 21]
after_state = [23, 25, 20, 24, 18, 22, 23, 28, 24, 25, 24, 20]
CI = 0.95
alpha = 1 - CI

# Null Hypothesis (Ho): The training program does not increase the max vertical jump of players.
# Alternate Hypothesis (Ha): The training program increases the max vertical jump of players.

# Perform Test.
test = stats.ttest_rel(a = after_state, b = before_state, alternative='greater')

print(f'Significace Lavel of test: {alpha}')
print(f'p-value of test: {test.pvalue}')

# Conclusion.
if test.pvalue < alpha:
    print('\nWe reject Null Hypothesis.')
    print(f'Hence, we conclude with {CI * 100}% confidence, \nThe training program increases the max vertical jump of players.')
else:
    print('We failed to reject the Null Hypothesis.')

Significace Lavel of test: 0.050000000000000044
p-value of test: 0.01401403729341254

We reject Null Hypothesis.
Hence, we conclude with 95.0% confidence, 
The training program increases the max vertical jump of players.


### Example

- A researcher noted the number of chocolate chips consumed by **10** rats, with and without the electrical simulations.

- Create a function **perform_ttest(sample1, sample2)** that accepts two parameters:

    - **sample1**: represents consumption with simulation.

    - **sample2**: represents consumption without simulation.

    - Compute the t-statistics of those two samples and return **t-score** and **p-value**.

- Test with the two random samples generated using **numpy** random module.

In [6]:
def perform_ttest(sample1, sample2):
    # Perform t-test.
    test = stats.ttest_rel(sample1, sample2)

    return {
        't-score': round(test.statistic, 4),
        'p-value': round(test.pvalue, 4)
    }

sample1 = np.random.randint(5, 20, 10)
sample2 = np.random.randint(4, 19, 10)

print('Sample 1:\n', sample1)
print('Sample 2:\n', sample2)
print('\nt-test results:')
for key, val in perform_ttest(sample1, sample2).items():
    print(key, ':', val)

Sample 1:
 [14 16 11  8  8  7 15 16 13 18]
Sample 2:
 [ 8 11 12 11 10  5  7 14  6 18]

t-test results:
t-score : 1.9354
p-value : 0.0849


#### Exmple

- A social scientist conducted an experiment on life stisfaction (computed through a special methodology) of older adults and younger adults.

- He collected two samples: **sample_old** and **sample_young** of life satisfaction scores of **10** individuls in each group.

- Create a function **perform_ttest(sample1, sample2)** where **sample1** and **sample2** are two independent samples. This function returns the **t-score and p-value** of the t-test.

- Test with the two random samples generated using **numpy** random module.

In [7]:
def perform_ttest(sample1, sample2):
    # Perform t-test.
    test = stats.ttest_ind(sample1, sample2)

    return {
        't-score': round(test.statistic, 4),
        'p-value': round(test.pvalue, 4)
    }

sample_old = np.random.randint(50, 100, 10)
sample_young = np.random.randint(50, 100, 10)

print('Life Satisfaction of Old Adults:\n', sample_old)
print('Life Satisfaction of Young Adults:\n', sample_young)

print('\nt-test results:')
for key, val in perform_ttest(sample1 = sample_old, sample2 = sample_young).items():
    print(key, ':', val)

Life Satisfaction of Old Adults:
 [94 92 70 67 70 58 84 83 59 57]
Life Satisfaction of Young Adults:
 [61 72 64 92 85 82 65 91 77 64]

t-test results:
t-score : -0.3293
p-value : 0.7457
