# Introduction to Statistical Modelling

### Statistical Model

- A **Statistical Model** is a mathematical equation, which explains the relationship between dependent variables (Y) and independent variables (X).

```Y = f(X)```

- However, in reality, an element of uncertainty is expected due to factors such as measurement noise.

```Y = f(X) + e, where 'e' is residual error```

- **Statistical Modelling** deals with creating models that attempt to explain the data best.

### Liner Model

- The simplest model is a **linear regression model** represented as ```Y = B0 + B1*X + e```, where the coefficients, **B0** and **B1** are the parameters of the model and **e** is normally distributed residual error. A liner regression model is fitted to data using *ordinary least squares (ols)* approach.

### Non-Linear Models

- Other than linear regression models, statistical modeling can be used to build non-linear models.

- Errors of dependent variable follow a distribution other than normal distribution.

- Examples of non-linear models are: **Binomial Regression** and **Poisson Regression**.

- In most of the cases, the non-linear models are generalized to linear models.

### Design Matrices

- In reality, you choose a model and fit the available data to it.

- Once a model is chosen, design matrices **Y** and **X** are constructed, and the regression problem is written, in matrix form, as ```Y = XB + e```.

- Where **Y** is the vector of dependent variables, **X** is the vector of independent variables, **B** is a vector of coefficients, and **e** is the residual (error).

- Thus obtained design matrices are passed as inputs to the chosen model.



## Statistical Modelling with StatsModels

- **statsmodels** library supports several types of statistical models.

- A Statistical model is represented by a model class.

- A model can be initiated with,

    - given design matrices of dependent and independent variables, or with
    
    - given patsy formula and data frame or dictionary-like object.



In [3]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf

# 1. Create Sample Data
data = {
    'Price': [200, 250, 300, 350, 400, 450, 500, 550, 600, 650],
    'Size_sqft': [1500, 1600, 1750, 1800, 1950, 2000, 2100, 2200, 2300, 2400],
    'Bedrooms': [3, 3, 4, 3, 4, 4, 5, 4, 5, 5]
}
df = pd.DataFrame(data)

# --- MODEL CREATION ---
# Formula: 'Dependent_Variable ~ Independent_Variable_1 + Independent_Variable_2'
# Here, we predict Price using Size_sqft.

model_formula = smf.ols('Price ~ Size_sqft', data=df)

# 2. Fit the Model
results_formula = model_formula.fit()

# 3. Print the Summary Table (Key step for statsmodels)
print("\n--- Model Summary (Formula API) ---\n")
results_formula.summary()


--- Model Summary (Formula API) ---



<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.995
Model:                            OLS   Adj. R-squared:                  0.995
Method:                 Least Squares   F-statistic:                     1707.
Date:                Sat, 13 Dec 2025   Prob (F-statistic):           1.30e-10
Time:                        13:23:27   Log-Likelihood:                -37.022
No. Observations:                  10   AIC:                             78.04
Df Residuals:                       8   BIC:                             78.65
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -568.4919     24.296    -23.399      0.000    -624.518    -512.466
Size_sqft      0.5069      0.012     41.315      0.000       0.479       0.535
==============================================================================
Omnibus:                        6.202   Durbin-Watson:                   2.675
Prob(Omnibus):                  0.045   Jarque-Bera (JB):                3.108
Skew:                          -1.365   Prob(JB):                        0.211
Kurtosis:                       3.092   Cond. No.                     1.39e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.39e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

#### Interpretation of Output:

The output summary table is the main strength of statsmodels. Key parts to look at:

- **R-squared:** Measures how well the model explains the variability in the data (closer to 1 is better).

- **const (Intercept):** The value of the dependent variable when all predictors are zero.

- **Size_sqft (Coefficient):** The estimated change in Price for a one-unit increase in Size_sqft.

- **P>|t| (P-value):** The probability that the coefficient is zero. A P-value less than a significance level (e.g., 0.05) indicates the variable is statistically significant.

## Output of OLS Regression Model

The output of OLS Regression Model consists of three main sections: **Model Information, Coefficients/Parameters, and Tests/Diagnostics**.



In [6]:
import numpy as np

# Formula: Y = B0 + B1*X1 + B2*X2 + B3*X1*X2

y = np.array([1, 2, 3, 4, 5])

x1 = np.array([6, 7, 8, 9, 10])
x2 = np.array([11, 12, 13, 14, 15])

X = np.vstack([np.ones(5), x1, x2, x1*x2]).T

print(y)
print(X)

[1 2 3 4 5]
[[  1.   6.  11.  66.]
 [  1.   7.  12.  84.]
 [  1.   8.  13. 104.]
 [  1.   9.  14. 126.]
 [  1.  10.  15. 150.]]


In [7]:
import patsy
import numpy as np

y = np.array([1, 2, 3, 4, 5])
x1 = np.array([6, 7, 8, 9, 10])
x2 = np.array([11, 12, 13, 14, 15])
data = {'y':y, 'x1':x1, 'x2':x2}

y, X = patsy.dmatrices('y ~ 1 + x1 + x2 + x1*x2', data)

print(y)
print(X)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[[  1.   6.  11.  66.]
 [  1.   7.  12.  84.]
 [  1.   8.  13. 104.]
 [  1.   9.  14. 126.]
 [  1.  10.  15. 150.]]
